# encoding: ASCII-8BIT
Post.create!(:title => 'La compresión del tiempo', :body => <<POST, :created_at => Date.new(2004, 10, 04))
Levantas la mirada, el cielo esta grisaceo, vacío y deprimente como todos los días de tu vida que puedes recordar. El suelo no está, las paredes se fueron, todo es cielo. El espacio ya se ha compactado, y ese sabor amargo que creíste no volver a sentir vuelve a recorrer por completo tu cuerpo y todos tus sentidos. El sólo recuerdo de anoche te destroza la cabeza. ¿Habrá sido verdad? Tus últimos años han sido una locura y ya no puedes diferenciar entre lo que sucede y lo que es delirio, entre el sueño y la realidad, entre lo que ves y lo que es, entre la historia y el pasado. Tratas de recomponer algunas escenas, pero los ruidos y los disturbios no te permiten hacerlo.

Te alejas un poco, querés ver todo un poco mas claro, querés ver las cosas desde afuera, desde otro ángulo. Pero es imposible. Te miras el brazo, las manos, los pies. Aunque no puedes dilucidar una idea entiendes, y comprendes, que tu vida es un desastre. Te sientes vacío, desnudo, dudas si tu alma sigue a tu lado o si se perdió en la inmensidad del espacio. La lucidez te vuelve a abandonar y el olor de los buenos años ya no es tan perceptible. Tu último tiempo fue una caida libre, una colisión a la velocidad de la luz, y la mano que te venía ayudando ya no está ahí. No está ahi; ni para vos, ni para tus amores; ni para vos, ni para tus rencores; ni para vos ni para...

Un espejo cruza el cielo, tratas de girar la cabeza para mirarte en él pero tu cuerpo se niega a hacerlo. Las ganas de estar y seguir y de ser ya no forman parte de vos. Ya no querés ni moverte ni pestañear. Comienzas a dudar si en realidad estas respirando. No querés fracasar, ni triunfar, ni siquiera zafar. Ya no querés. Tan solo piensas en olvidar lo que fuiste y despreocuparte de lo que va a ser de vos. Solo te importa dejar este dolor que te aprisiona y te encierra, sino podés dejarlo, aunque sea, amarlo.

Un pétalo cae sobre tu nariz, otra rosa marchita en tu vida cruzando tu camino. Otra triste desazón... Tu mente se aligera, el pasado es ahora y el futuro ya fue... tiemblas y te estremeces, el ahora se volvio muy distante pero, tu niñez y lo que creiste que ibas a ser estan juntos de nuevo. Te vuelves a sentir ligero como una pluma y te imaginas como serás cuando seas un bebé. El presente pasó hace tanto que apenas lo recuerdas.

bq. _Todo termina en el comienzo al igual que el fin desemboca en el nudo..._
POST

Post.create!(:title => 'Mi mano me lo pidió a gritos', :body => <<POST, :created_at => Date.new(2004, 11, 21))
Un tiempo maravilloso fue el nuestro juntos. En todo momento sentí que eramos el uno para el otro. La forma en que me mirabas, como me hacias sentir, tu forma de hablar y de ser. Tu hermoso cuerpo casi perfectamente esculpido que, facilmente, sería la envidia de cualquier escultura de Miguel Ángel o Rodín.

Pero había algo, algo que no me cerraba. En otro de nuestros típicos paseos, rumbeando por la vida, fue cuando me di cuenta. Ahí comprendi por qué sentía ese malestar en mi mano derecha cuando estaba cerca tuyo. Pues lo que sentía era sutil, pero constante. ¿Viste esas sensaciones que comienzan en una parte del cuerpo y, de a poco, comienzan a recorrerte cada célula del mismo? Algo así como un cosquilleo, pero con la agudeza de un gran calambre. Como un hormigueo, pero provocado por una corriente eléctrica constante que pareciera que no fuera a detenerse pero de pronto cesa. Como decía, estabamos rumbeando por nuestra ciudad, disfrutandonos uno al otro. Casi que recuerdo cada detalle, debido al impacto que me causó, habíamos entrado a esa tienda llena de espejos en busca de chucherías. Yo tenía mi brazo alrededor de tu pequeña y perfecta cintura, y no podía dejar de pensar en la noche anterior y en lo bien que la habíamos pasado. Por un segundo mi mente volvió a tierra y lo vi, ahí fue cuando comprendí la extraña sensación. El espejo lo mostraba claramente. ¡Era tan simple! ==¡NO COMBINÁS CON MI MANO DERECHA!==

Miles de ideas comenzaron a cruzar mi mente. Todas y cada una de ellas fueron descartadas, nada salvaba la situación.. No había forma de arreglarlo. Me alejé corriendo negando todo a esconderme un tiempo. Recientemente volví a la luz, y luego de un tiempo tomé coraje y vine hasta aquí, para despedirme.

¡Que triste es cuando las despedidas son por pequeños descuidos de uno!... Pensar... Que si lo hubiera notado antes ahora no estarías sufriendo por nuestro adios, tan solo porque nunca hubiera habído un comienzo ni nada entre nosotros. Inconcientemente me descuidé y no tomé la precaución de fijarme si hacías juego con mis dedos, mis uñas o mi muñeca.

Espero entiendas que lo nuestro no puede ser. Quizás, mi mente soñadora me permite pensar, algún día seas diferente y tu cuerpo concuerde con la estética de mi mano... pero ahora no. No lo veas como una despedida, tan sólo como un descuido, algo que no debió ser. En cuanto a mi, seguiré buscando, pero, esta vez, con mas cuidado, para no volver a lastimar.
POST

Post.create!(:title => 'Vengo de un toc-toc, nada de tequila shot...', :body => <<POST, :created_at => Date.new(2004, 12, 04))
Junté mis esperanzas en una fiesta. De esas que se hacen cuando somos niños pero queremos dejar de serlo, con juegos de índole libidinosa, que, en esos entonces, no entendíamos tanto. La vi girar en el centro de la ronda, verde fiesta como el vestido de Adela. No era otra cosa que una botella de gancia completamente vacía... _girando y girando..._ la verdad ya había sido consecuencia de una noche agitada que solo quería terminar en silencio, pero no sin la acción necesaria.

La habitación comenzó a llenarse de susurros, murmullos y suspiros, mientras una presión interminable crecía en mi pecho. Mis ojos se fijaron en ese verde "esperanza" y pensé "¡Loco, loco! Parece el mundo, gira y gira, todo rodeado de personas. - _Definitivamente parecía la tierra_ -. ¿Tierra? Como diría _Peke_, ¿Por qué tierra? ¿Si está toda cubierta de agua?... Agua, del latín, Aqua... jeje... como el grupo Aqua de los años 90, definitivamente toda una 'barbie girl' la que tenía enfrente mío, o, como diría Luca, _una rubia tarada_".

Lentamente comenzó a cesar su giro, lentamente, los susurros, murmullos y suspiros empezaron a detenerse, pero la presión en mi pecho tan sólo se hacía mas fuerte. Quería arrancarme la camisa, pero recorde que estaba en cueros y sudando como un cerdo. Quería correr, pero recordé que estaba acostado y durmiendo. ¿Noche agitada? No, tán solo sueños agitados. Vodka y Sprite = Toc-Toc... ¿Quién es? ¿Llamaron a la puerta? No, no es nadie, tan solo me pareció... igual, se que el amor debe estar por llegar a mi puerta... No es su culpa, es que con todos estos paros de subte se le debe haber complicado un poco, y siempre me dijeron que no tenía mucha ubicación, por ese tema de que es no vidente... Pero, que se yo... Si usa bien el GPS va a llegar, digo yo, ¿No?
POST

Post.create!(:title => 'Manto blanco', :body => <<POST, :created_at => Date.new(2004, 12, 20))
¿Cómo ser como soy? ¿Cuántas veces lloraste sobre mí buscando otro consuelo a tus noches? ¡Nunca me cuentas tus secretos! ¿Es que la prefieres a ella, con lo gorda que está? No te preocupes, con todo lo que te quiero no hay distancia que evite que te escuche entre tus sollozos y murmullos, por eso te entiendo. Me encantan cuando vienes a mi en compañía. ¡Esas risas y vueltas realmente me llenan de vida! Esos juegos y giros me me renuevan de punta a punta. Me siento alta y lejos, casi siento que toco el cielo. Toda una montaña rusa son esas noches. Pero no te amo sólo por eso. También me encanta verte serena mientras te abrazo con todo mi ser, amo velar por ti mientras duermes.

Te conozco tanto que si pudiera hablar ya me estarías callando, y se cuánto me extrañarías si no estuviera. Después de todo, una cama sin mi no es mas que eso. Todas las noches que te tengo recorro tu cuerpo vuelta y vuelta porque sé que de luego me espera un largo día sin vos. Las noches que me faltas también son largas, pero las sobrellevo pensando cuanto que voy a disfrutar tu regreso, y que, cuando tu cuerpo se desplome, yo estaré ahí para vos. En las noches de calor termino besando tus hermosos pies y las de frío no dejas que me aparte ni un milímetro de vos. Nunca habrá nadie como yo para vos. Ninguna colcha, frazada, ni almohada. Soy lo que soy, y así me quieres, bien *blanca*.
POST

Post.create!(:title => 'My Ma|)neSs', :body => <<POST, :created_at => Date.new(2005, 2, 3))
Definitivamente, no hay nada mejor que poder ver lo que otros no ven. El sentir las cosas de manera diferente. El poder soñar con los ojos abiertos, pero sin la ayuda de nada mas. Hablo de esa cualidad que se ve en pocas personas, mas que personas, yo diría, afortunados. Una mente soñadora abierta y con un poco de locura.

El otro día discutía esto en el msn. La locura sana definitivamente es una buena cualidad en la gente. Sólo la tienen algunos. Ese toquecito soñador y delirante que nos ayuda a muchos a ver el mundo de otra manera y sobrevirlo sin que esto implique tener que sufrirlo. No nos salva de nada. Tampoco evita el lastimarse. Mucho menos te soluciona la vida. ¡Cruz diablo! Que si fuera asi, definitivamente, no la quisiera tener. Porque... ¿Para que alguien podría llegar a querer una vida que esté toda solucionada? ¡¿Cómo podría llamarse a eso vida?!

No hablo de no estar sano mentalmente y tampoco hablo de la locura que es consecuencia inevitable en los comienzos de un amor. Esa locura, la del amor, aunque es de lo mejor que le puede pasar en su corta existencia al ser humano, con el tiempo se torna burda, vulgar, diría yo, y incluso a veces, vista de lejos, no es mas que absurda. Yo hablo de la locura soñadora, la que te da esperanzas, la que te permite imaginar y volar, pero sin despegar los pies de la tierra (al menos, sin despegarlos mucho), sin dejar de saber que sucede y que no. Es cierto que a veces puede confundirte, pero no mucho mas que eso. En este mundo tan asesino, tan hipócrita, tan corrupto, y con tanta maldad no hay que dejar de creer que se puede cambiar. Porque nuestro mundo actual no hay nada mas lejos de la realidad que este mundo se vuelva un "edén". Por eso necesitamos este tipo de gente, este tipo de "artistas", soñadores que no se asusten de la mierda que hay en este mundo ni sean corrompidos por esta. Hay que ver las cosas desde todos los lugares que se pueda para comprenderlas mejor y poder encontrar soluciones. Si la tienen, no la pierdan. ¡¡Sueñen!!!

bq=. *"Open your mind, be 'wild'"*
POST

Post.create!(:title => 'Oído al pasar', :body => <<POST, :created_at => Date.new(2005, 9, 26))
Dicen que me dijeron que una noche, una de esas calmas en las que se oyen susurros de seres desesperados por fundir su alma y corazón con una estrella que les corresponda en su totalidad, se fue de viaje un místico duende llamado Cernud en busca del brillo perdido en sus ojos. Corrió a traves de mares de lágrimas, navegó por cielos de algodones de azucar, y voló por toda la tierra media. Entró al averno enfrentando colores y brisas que lastimaban su piel y oídos. Visitó el cielo y a todos sus Dioses sin encontrar señal alguna de su tesoro perdido. Decepcionado de tan árdua tarea sin logarar su objetivo, finalmente decidió descansar sobre los verdes campos de la amplia ciudad de Bazhora. Apoyó suavemente su alforja en el árbol que se posaba en lo mas alto de una colina y, usandola de almohada, cerró sus ojos. Una minúscula, suave y dulce lagrima recorrió lentamente sus secas y tristes mejillas, y, finalmente, cayó a su lado. De ese grito de desolación, surgió una diminuta planta, la cual dio lugar a una pequeña flor que al abrirse dió nacimiento a un hada de ensueños. Al ver lo sucedido el duende olvidó por completo su búsqueda y dedicó el resto su vida a este ser que apareció en el momento en que creia que todo estaba perdido. A pesar que Cernud envejecía su mirada se veía cada día mas joven y, día a día, junto a su hada, recuperaba poco a poco el brillo original que había perdido. Por lo menos, es lo que dicen que dijeron que sucedió.
POST

Post.create!(:title => 'Vuelos', :body => <<POST, :created_at => Date.new(2006, 1, 26))
No hacen falta alas para cruzar límites, pero sí una mente abierta para saber que hay ciertas fronteras que si se pueden atravesar aunque otros digan lo contrario. Esos ojos soñadores son los que pueden ver mas allá en los momentos en que la realidad se nos presenta tan cerca que nos causa escalofríos. Esta vez no hablo de ninguna transgresión, ni de nada ilegal, probablemente sea de lo mas sano que conozco en este mundo, a pesar de que algunos se encuentren encerrados por el exceso incontrolado.

Muchas veces, en muchos lados, hable con diversa clase de gente y suelo preguntar, en las largas discuciones filosóficas, si creen que se puede volar sin alas y si suelen soñar despiertos. Algunas veces las respuestas que he recibido a tales preguntas me han roto el corazón. He sido varias veces desilucionado con una rotunda y súbita negación ante lo planteado, y una mirada fija, con cara extraña, como diciendo: "¿De dónde lo sacaron a este demente?". Por suerte no suelo quedarme con una opinión. Dificilmente me convenzan varios pares de miles de opiniones. Sobre todo cuando, de tanto en tanto, aparece alguien inusual que te hechiza hablandote del viento soplando en su cara al momento de cruzar los cielos. Esa emoción de escuchar a alguien relatar sus sueños vividos con una sencillez que desvela me atrapa de manera casi superior a los momentos en que yo mismo despego del piso.

Probablemente las palabras sean lo mas poderoso que el ser humano posea. En, tan solo instantes, dos personas pueden dejar el lugar físico y real en el que se encuentran en ese preciso instante y, lentamente, abandonar la tierra que se encuentra bajo sus pies para poder llegar a algún sitio en el que se encuentren mucho mas cómodos y seguros. Puede que ese lugar ya lo hayan visitado, o que simplemente haya sido creado por y para ellos en ese instante y se destruya luego de abandonarlo o, quien sabe, puede que perdure mas allá de la eternidad.

Tuve alas que se desplegaban en alguna ventana de una Begonia. Bajé estrellas con tan solo un simple y suave salto. Fui un "SuperStar" en busca de su "True Love". Fui gusano que luego soñó con mariposas. Hablé con duendes provenientes de la peninsula Ibérica. Separé mi parte humana de mi parte aviária para luego arrojarla lejos de mi en un "ritual" que consumió mucho de mi buena persona. Comí insectos y fumé mucho, pero mucho, "Denim". Todo esto entre otras tantas cosas, que no recuerdo o no quiero recordar. Por estos actos que desafían la realidad me han tildado de "drogadicto", "chamushero" e inclusive demente, pero, es esa sonrisa que se desprende de los labios, que no siempre se ve, la que me inspira y me convierte cada vez mas en lo que soy. Algún día si me escuchan puede que se rían, pero sepan que tan solo cuento lo que siento.

bq. "Cuento lo que siento pero no cuento todo lo que amo.
Vivo en el viento para cruzar tu pelo y entrar por tus oidos.
Sueño en el mar, para lavar tu cuerpo y aplacar tu sed.
Estoy en la tierra, porque de ahi vengo y nunca me iré.
Soy una nube, para estar cerca del sol y llorar cuando me plazca.
Soy lo que soy... y no pretendo ser mas..."
POST

Post.create!(:title => 'Nuestro mundo rosa', :body => <<POST, :created_at => Date.new(2006, 2, 6))
Mas allá de los cuentos de hadas, de las mentiras sobre "como venimos al mundo", de los gordos en batas rojas o de los duendes *buenos*; nuestros queridos viejos nos han mentido en un momento crucial de nuestras vidas. Nos han mentido en el momento de entregarnos al mundo cruel y satánico en el que vivimos. La vedette de todas estas mentiras y que todos nos llegamos a convencer es: "El mundo *no* es color de Rosa".

Todo un palo. YA LO VES! Veamoslo un poco con mis ojos *~_^*

h4. Nuestra guía en este post será la %{color:#e1b7b7; text-transform: uppercase}rosa de los vientos%.

* Fin de semana, te querés sentir jóven, renovado, con todas las energias! En esos momentos el mundo se transforma ante tí convirtiendose en un rosa Viejo.
* Finalmente se terminan las clases de la facu y el jefe decide darte vacaciones... Esperás poder broncearte un poquito y sacarte esa cara de muerto que tenés. Sin embargo, al volver, entiendes que tu mundo es un rosa pálido.
* Día agotador en lo que sea que tengas que hacer. Estás todo estresado, solo pensás en volver al confort de tu casa, tirarte en la cama y descansar... el mundo no hace mas que gritarte a la cara lo rosa chillón que puede ser.
* En esos días de felicidad, la vida te mira desde el cielo, tras un marco de seguridad, y cuando logras enfocar tu vista, ya que el sol te enceguece, puedes ver un rosa, un rosa triste que se apodera de ti.
* Noche en Bs.As., te pudiste levantar y vencer al mal humor, al cansancio, y a la vejez! Miras a tu alrededor buscando alguna conquista que te acompañe aunque sea por una noche. ¡Pero ya lo vés! el mundo es rosa... un rosa *BIEN* gay ;)~

h4. Pero todos sabemos que la vida y nuestro mundo son un regalo, y, como toda rosa, _algo que no le faltan son_ %{color: green}*espinas*%.
POST

